### ISSUE TITLE
l10n bot appears to ignore a particularly long string?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/docker-ci#125]
As seen in https://github.com/nextcloud/bookmarks/pull/621, the string defined [here](https://github.com/nextcloud/bookmarks/blob/master/js/templates/EmptyBookmarks.html#L2) appears not to get picked up by the bot.

**Comment by MorrisJobke** [comment]
Weird - it seem to be not related to the length, because if I delete the first entry from that file the string is extracted properly. Looks like it stops after the first finding. 🤔

**Comment by MorrisJobke** [comment]
I guess this is related to the fact, that it uses this template language. We try to map this HTML file as JS and tell xgettext, that it should look for JS functions. But due to the HTML tags it doesn't find the two distinct occurrences :/

Also I have no idea how to fix this properly except writing our own extractor for this kind of syntax 😢

**Comment by marcelklehr** [comment]
This will have to wait until the bookmarks app is converted to vue, then.
